rustup: add the missing + in the install
Otherwise, it can fail with:
error: error: Invalid value for '<+toolchain>': Toolchain overrides must begin with '+'